server:
  port: 8082
  shutdown: graceful

spring:
  application:
    name: pedido-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  mvc:
    problemdetails:
      enabled: true
  cloud:
    openfeign:
          client:
            config:
              default:
                connect-timeout: 2000     # 2s
                read-timeout: 5000        # 5s
                logger-level: basic

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,threaddump,httpexchanges
  endpoint:
    health:
      show-details: when_authorized

notificacao:
  base-url: ${NOTIFICACAO_URL:http://localhost:8081}

logging:
  level:
    io.junior.pedido.infra.NotificacaoClient: DEBUG
    org.springframework.cloud.openfeign: INFO
